### ISSUE TITLE
Can't Use from UWP Project

### ISSUE THREAD

**Issue by Yortw** [danvy/kloutsharp#2]
Hi,

It seems the Nuget published version can't be used from a UWP project. The nuget package installs, but no namespaces or classes show up. Obviously I can work around this by including the source or making my own fork etc, but I would prefer to use the officlal nuget package to make future updates etc easy. Is there any possibility of a published update that supports UWP projects?

Thanks.

**Comment by danvy** [comment]
Hi, latest version now supports UWP. Thank you for your feedback :)

**Comment by Yortw** [comment]
Excellent, thanks 😊
